-- 자식이 있기 위해서는 자기 자신의 아이디가 누군가의 부모 아이디가 되어야함
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO
INNER JOIN ITEM_TREE
ON  ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
WHERE ITEM_INFO.ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID 
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_INFO.ITEM_ID DESC;
