 SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM (SELECT
      FI.ID, FI.FISH_TYPE, FI.LENGTH
      FROM FISH_INFO FI
      INNER JOIN 
      (SELECT
      FISH_TYPE, MAX(LENGTH) LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) MFI
      ON FI.FISH_TYPE = MFI.FISH_TYPE AND FI.LENGTH = MFI.LENGTH) A
      INNER JOIN FISH_NAME_INFO B
      ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.ID
                  
   