SELECT A.FISH_COUNT, A.MAX_LENGTH, A.FISH_TYPE
FROM (SELECT 
      FISH_TYPE,
      AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AVG_LENGTH,
      MAX(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) MAX_LENGTH ,
      COUNT(FISH_TYPE) FISH_COUNT
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG_LENGTH >= 33) A
ORDER BY A.FISH_TYPE;